openapi: 3.0.0
info:
  title: Typing Game API
  description: API documentation for Typing Game project
  version: 1.0.0
servers:
  - url: https://typecode.app/
    description: Remote server
paths:
  /api/signup:
    post:
      summary: Register a new user
      description: Endpoint for registering a new user with first name, last name, email, login, and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                login:
                  type: string
                password:
                  type: string
              required:
                - firstName
                - lastName
                - email
                - login
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: Error - User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/login:
    post:
      summary: User login
      description: Endpoint for user login with login and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
                - login
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid login or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string