name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Move Frontend Build to Backend
      run: |
        rm -rf ./backend/src/client/dist
        mkdir -p ./backend/src/client/dist
        cp -r ./frontend/dist/* ./backend/src/client/dist/

    - name: Compile backend
      working-directory: ./backend
      run: |
        npm install
        tsc

    - name: Install Rsync if Not Installed
      run: |
        if ! command -v rsync &> /dev/null; then
          echo "Rsync not found. Installing..."
          sudo apt-get update && sudo apt-get install -y rsync
        else
          echo "Rsync is already installed."
        fi

    - name: Deploy to Server
      env:
        SERVER_USER: root
        SERVER_HOST: typecode.app
        DEPLOY_PATH: /root/deployment
      run: |
        # Sync built project files to the server
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
        rsync -avz --exclude=".git" --exclude="node_modules" ./backend $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "pm2 restart prod"

